site_name: Deepseek - Grupo 2
site_author: Ana Borges, Ana Joyce, Davi, Fabio, Gabriela, Luiz e Mateus
site_description: Site voltado para a documentação do Grupo 2 de Requisitos de Software
repo_url: https://github.com/Requisitos-de-Software/2025.1-Deepseek
repo_name: 2025.1-Deepseek

theme:
  name: material
  logo: 'images/deepseek.svg'
  favicon: 'images/deepseek.svg'

  palette:
    - scheme: default
      primary: "#4D6BFE"
      accent: "#4D6BFE"
      toggle:
        icon: material/brightness-7   
        name: Switch to dark mode

    - scheme: slate
      primary: "#4D6BFE"
      accent: "#4D6BFE"
      toggle:
        icon: material/brightness-4   
        name: Switch to light mode

nav:
  - Visão Geral: index.md
  
  - Gravações:
    - Entregas: 'gravacoes/entregas/grav-entrega.md'
    - Reuniões: 'gravacoes/reunioes/grav-reunioes.md'
    - ATA 10-04-2025: 'gravacoes/reunioes/ata-dia-10-04-2025.md'
    - ATA 15-04-2025: 'gravacoes/reunioes/ata-dia-15-04-2025.md'
    - ATA 17-04-2025: 'gravacoes/reunioes/ata-dia-17-04-2025.md'
    - ATA 24-04-2025: 'gravacoes/reunioes/ata-dia-24-04-2025.md'
    - ATA 29-04-2025: 'gravacoes/reunioes/ata-dia-29-04-2025.md'
    - ATA 01-05-2025: 'gravacoes/reunioes/ata-dia-01-05-2025.md'
    - ATA 06-05-2025: 'gravacoes/reunioes/ata-dia-06-05-2025.md'
    
  # - Pré-Rastreabilidade:
  #   - Rich-Picture: 'pre-rastreabilidade/rich-picture.md' 
  
  - Planejamento:
    - Políticas do Repositório:
        - Branches: 'planejamento/politicas_repositorio/politica_branches.md'
        - Commits:  'planejamento/politicas_repositorio/politica_commits.md'
    - Cronograma:              'planejamento/cronograma.md'
    - Cronograma Executado:    'planejamento/cronograma-executado.md'
    - Ferramentas:             'planejamento/ferramentas.md'
    - Heatmap:                 'planejamento/heatmap.md'
    - Lista de Apps Avaliados: 'planejamento/lista-de-apps-avaliados.md'
    - Termo de Uso:            'planejamento/termo-de-uso.md'

  - Técnicas de Elicitação:
    - Requisitos Elicitados: 'elicitacao/requisitos-gerais.md'
    - Análise de Documentos: 'elicitacao/analise-de-documentos.md'
    - Pesquisa/Questionário: 'elicitacao/questionario.md'
    - Observação: 'elicitacao/observacao.md'
    - Análise de Interface: 'elicitacao/analise-de-interface.md'

  - Perfil de Usuário: 'elicitacao/perfil-de-usuario.md'

  - Técnicas de Priorização:
    - MoSCoW: 'priorizacao/MoSCow.md'
    - Three Level Scale : 'priorizacao/three-level-scale.md'
    - In-or-Out: 'priorizacao/In-or-Out.md'
    - Quality Function Deployment: 'priorizacao/QFD.md'
  
  - Modelagem:
    - Cenários: 'modelagem/cenarios.md'
    - Casos de Uso: 'modelagem/casos-de-uso.md'
    - Léxicos: 'modelagem/lexicos.md'
    - Especificação Suplementar: 'modelagem/especificacao-suplementar.md'

  - Verificação:
    - Segunda Entrega: 'verificacao/segunda-entrega.md'

  - Inspeção:
    - Segunda Entrega: 
      - Grupo 2: 'inspecao/entrega2/inspecao-grupo.md'
      - Grupo 3: 'inspecao/entrega2/inspecao-grupo3.md'

  - Projeto Obsoleto:
      - Início: 'doc-guardioes-da-saude/index.md'
      
      - Gravações:
          - Entregas: 'doc-guardioes-da-saude/gravacoes/entregas/entregas.md'
          - Reuniões:
              - Visão Geral: 'doc-guardioes-da-saude/gravacoes/reunioes/reunioes.md'

      - Planejamento:
          - Políticas do Repositório:
              - Branches: 'doc-guardioes-da-saude/planejamento/politicas_repositorio/politica_branches.md'
              - Commits:  'doc-guardioes-da-saude/planejamento/politicas_repositorio/politica_commits.md'
          - Cronograma:              'doc-guardioes-da-saude/planejamento/cronograma.md'
          - Ferramentas:             'doc-guardioes-da-saude/planejamento/ferramentas.md'
          - Heatmap:                 'doc-guardioes-da-saude/planejamento/heatmap.md'
          - Lista de Apps Avaliados: 'doc-guardioes-da-saude/planejamento/lista-de-apps-avaliados.md'
          - Lista de Verificação:    'doc-guardioes-da-saude/planejamento/lista-de-verificacao.md'
          - Rich Picture:            'doc-guardioes-da-saude/planejamento/rich-picture.md'
          - Termo de Uso:            'doc-guardioes-da-saude/planejamento/termo-de-uso.md'

      - Técnicas de Elicitação:
        - Pesquisa/Questionário: 'doc-guardioes-da-saude/tecnicas-de-elicitacao/questionario/ElicitacaoQuestionario.md'
        
markdown_extensions:
  - pymdownx.details
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - css/custom.css

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js